version: "2"
services:
  app:
    container_name: app
    image: node
    volumes:
      - .:/app
    command: npm run dev
    working_dir: /app
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo:/data/db/
    ports:
      - "27017:27017"
